// <auto-generated />
namespace Compactor.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class FromEquipmentToDevice_AddedIsActivInReservation_UserIdInPosition : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FromEquipmentToDevice_AddedIsActivInReservation_UserIdInPosition));
        
        string IMigrationMetadata.Id
        {
            get { return "202210101725393_FromEquipmentToDevice_AddedIsActivInReservation_UserIdInPosition"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
